### ISSUE TITLE
Dynamischer Dorfwechsel 

### ISSUE THREAD

**Issue by Ichaelus** [Ichaelus/Gentle-Script#1]
- Neue Einstellung "dynamischer Dorfwechsel"
  Soll bei:
- Neuen Nachrichten
- Antworten
- Neuen Threads
- Antworten im Forum
- evtl. Chat

Nachfragen bevor das Dorf gewechselt wird

**Comment by Ichaelus** [comment]
" Bitte mach das Script so, dass er auch die Seite nicht wechselt, wenn die Einstellungen des Scripts offen sind. Das nervt ein bisschen, wenn man die Bauliste editiert und er mir die Seite vor der Nase wegwechselt und dann nichts gespeichert ist."

**Comment by Ichaelus** [comment]
"Bitte mach das Script so, dass er auch die Seite nicht wechselt, wenn die Einstellungen des Scripts offen sind. Das nervt ein bisschen, wenn man die Bauliste editiert und er mir die Seite vor der Nase wegwechselt und dann nichts gespeichert ist."

**Comment by reloxx13** [comment]
Eventuell wäre es global gut, wenn das Dorf bei Benutzertätigkeiten nicht gewechselt wird (unterbrich bei Mausmove, 1min pause oÄ).

**Comment by Ichaelus** [comment]
Gute Anmerkung, da ist noch zu überlegen wie man das ressourcenschonend flächendeckend überprüft. Würde ich eventuell in Folge nach dem eigentlichen Issue umsetzen, wieder mit einer eigenen Einstellung.

LG und danke fürs Feedback!

**Comment by Ichaelus** [comment]
"Desweiteren solltest du darauf achten, dass du nicht Aktionen des Bot's mit dem Seitenwechsel unterbrichst^^ So wechselt der Bot zum Beispiel die Seite, wenn er gerade die Map nach Barbarendörfern absucht.
Der Bot sollte generell nicht die Seite wechseln, wenn man am Einstellungen machen ist"

**Comment by reloxx13** [comment]
Weitere Alternative:
Play/Pause Button klein i-wo in dem Botmenü machen. 
Wenn man selbst am hantieren ist drückt man eben Pause und später wieder auf Play.
Ist wahrscheinlich auch die einfachste Lösung, da es die gleiche Funktion wie die Checkbox unter Einstellungen hat. Aber bitte nicht zu große Buttons :)

**Comment by Ichaelus** [comment]
Die Lösung gefällt mir definitiv am Besten, gute Idee!

**Comment by Ichaelus** [comment]
Mit dem nächsten Update wird folgendes Verhalten umgesetzt: Beim Klick auf den Ladebalken kann das Laden pausiert / fortgesetzt werden.

LG
