### ISSUE TITLE
Script lädt manchmal nicht

### ISSUE THREAD

**Issue by reloxx13** [Ichaelus/Gentle-Script#11]
Manchmal wird das Script gar nicht geladen oder der blaue Balken läuft nicht zum Dorfwechsel.

Dabei steht im LocalStorage unter 

***Mr.M***A gentle DS script - relaunch***LOCAL_SCRIPT
```
<br /> <b>Warning</b>: ...on line <b>2</b><br /> 	localStorage	https://de126.die-staemme.de:443		
Wert
<br />
<b>Warning</b>:  require(): open_basedir restriction in effect. File(/data/web/e44294/html/Michael/GS_Relaunch/require.php) is not within the allowed path(s): (/data/web/e44294/html/Michael/classifier:/data/web/e44294/phpsession:/data/web/e44294/phptmp:/tmp:/usr/bin) in <b>/data/web/e44294/html/Michael/GS_Relaunch/ajax.php</b> on line <b>2</b><br />
<br />
<b>Warning</b>:  require(/data/web/e44294/html/Michael/GS_Relaunch/require.php): failed to open stream: Operation not permitted in <b>/data/web/e44294/html/Michael/GS_Relaunch/ajax.php</b> on line <b>2</b><br />
<br />
<b>Fatal error</b>:  require(): Failed opening required 'require.php' (include_path='.') in <b>/data/web/e44294/html/Michael/GS_Relaunch/ajax.php</b> on line <b>2</b><br />
```

(Nach löschen des TimeStamps und damit verbundenen Neuladen des Scriptes lädt es wieder korrekt)

Lösungsvorschlag: Abfangen ob was anständiges in LOCAL_SCRIPT steht, wenn nicht neuladen.
oder
Serverfehler ausfindig machen

**Comment by Ichaelus** [comment]
Vielen Dank für die Fehlermeldung, der Fehler wurde in 4.321 behoben, man muss GS aber von der Homepage aus neu installieren.
Zugegebenermaßen war eine Abfrage ohne try..catch relativ leichtsinnig :)

LG
