### ISSUE TITLE
Funktionen im UV Modus

### ISSUE THREAD

**Issue by reloxx13** [Ichaelus/Gentle-Script#13]
Huhu,

wenn man in einer UV eingeloggt ist, ist der Bot unbrauchbar.

Wenn wäre daher gut, wenn zumindets die Vor- und Zurück Buttons sowie die Premium Bar funktionierne würden.

Bei Klick auf einen der genannten Funktionen landet man wieder im eigenem Dorf.
Einstelungen werden auch nicht gespeichert, aber damit kann man noch leben.

Es liegt vermutlich an dem fehlenden Parameter t in der Adresszeile.

&t=1234567890

**Comment by Ichaelus** [comment]
Danke für den genauen Bugreport, der Parameter war tatsächlich Teil des Fehlers. sollte nun funktionieren - Tests sind gerne willkommen
