### ISSUE TITLE
Bild kann nicht resolved werden

### ISSUE THREAD

**Issue by stevenklar** [Ichaelus/Gentle-Script#18]
https://bytebucket.org/Ichael/gentlescript/raw/239cb656c191e7786477c6fa3e41f72f564a7979/main_bg.jpg?token=13fd4077d400e7bcdaa4babb0b54fc0916459a6c

API Token invalid

**Comment by Ichaelus** [comment]
Danke, habe den static content nun zu GitHub verschoben.
