### ISSUE TITLE
Bei Baulisten automatisch ans Ende scrollen

### ISSUE THREAD

**Issue by Ichaelus** [Ichaelus/Gentle-Script#8]
"Könntest du, wenn man die Bauliste öffnet (zum editieren oder was auch immer), automatisch bis zu dem Eintrag scrollen, den diese als nächstes abarbeiten will?"

**Comment by reloxx13** [comment]
Das muss nicht sein, sieht man ja wenn man in der Hauptgebäudeansicht ist.

**Comment by Ichaelus** [comment]
Danke für dein Feedback. Es gibt auch immer die Möglichkeit, optimale Verhaltensweisen mit einer Option zu versehen.

**Comment by Ichaelus** [comment]
Eingebaut in Version 3.33
